"""Trace matrix artifact resolver.

Resolves trace-matrix-epic-{N}.md artifacts.
Used in retrospective to include traceability information.

Note (F19 Fix): Trace matrix may not exist on first retrospective
as it is generated BY the trace workflow during epic teardown.
"""

from __future__ import annotations

import logging
from typing import TYPE_CHECKING

from bmad_assist.testarch.context.resolvers.base import BaseResolver
from bmad_assist.testarch.paths import get_artifact_patterns

if TYPE_CHECKING:
    from bmad_assist.core.types import EpicId

logger = logging.getLogger(__name__)


class TraceResolver(BaseResolver):
    """Resolver for trace matrix artifacts.

    Loads trace-matrix-epic-{N}.md files.
    Epic-level artifact used in retrospective.

    """

    @property
    def artifact_type(self) -> str:
        """Return artifact type identifier."""
        return "trace"

    def resolve(
        self,
        epic_id: EpicId,
        story_id: str | None = None,
    ) -> dict[str, str]:
        """Resolve trace matrix artifact.

        Args:
            epic_id: Epic identifier (int or str).
            story_id: Not used for trace (epic-level artifact).

        Returns:
            Dict with single entry {path: content} or empty dict.

        """
        result: dict[str, str] = {}

        # Get pattern for trace matrix
        patterns = get_artifact_patterns(self.artifact_type, epic_id)
        subdir = self._get_artifact_dir()

        for pattern in patterns:
            matches = self._find_matching_files(pattern, subdir)
            if not matches:
                continue

            # Take first match
            path = matches[0]
            content = self._safe_read(path)
            if content is None:
                continue

            # Apply token truncation
            truncated = self._truncate_content(content, self._max_tokens)
            result[str(path)] = truncated

            logger.info(
                "TEA context: loaded %s (%s)",
                self.artifact_type,
                path.name,
            )
            return result

        # F19 Fix: Trace matrix may not exist on first retrospective
        # Log at INFO (not warning) since this is expected for first run
        logger.info(
            "TEA artifact not found: %s for epic %s (may not exist yet)",
            self.artifact_type,
            epic_id,
        )
        return result
