# Hardening - Retrospective Action Item Implementation Workflow
name: "hardening"
description: "Generates a Story 0 (Hardening Story) based on the latest Retrospective Report to ensure action items are prioritized."
author: "bmad-assist"

config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
user_skill_level: "{config_source}:user_skill_level"
document_output_language: "{config_source}:document_output_language"

installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/hardening"
template: false
instructions: "{installed_path}/instructions.md"

standalone: true
