# Synthesis workflow for Master to evaluate and apply validator findings
name: validate-story-synthesis
description: "Master synthesizes validator findings and applies changes to story file"
author: "BMad"

# Critical variables from config
config_source: "{project-root}/_bmad/bmm/config.yaml"
user_name: "{config_source}:user_name"
communication_language: "{config_source}:communication_language"
document_output_language: "{config_source}:document_output_language"
date: system-generated
planning_artifacts: "{config_source}:planning_artifacts"
implementation_artifacts: "{config_source}:implementation_artifacts"

# Workflow components
installed_path: "{project-root}/_bmad/bmm/workflows/4-implementation/validate-story-synthesis"
instructions: "{installed_path}/instructions.xml"
template: false

variables:
  epic_num: null
  story_num: null
  session_id: null
  validator_count: null

# No input_file_patterns - context provided programmatically by SynthesisCompiler
# The compiler embeds: project_context.md, story file, anonymized validations

standalone: true
